site_name: Documentation Membership Area

theme:
  name: material

nav:
  - Início: index.md
  - Entrega 1:
      - Home: entrega-1/home.md
      - PM Canvas: entrega-1/pm-canvas.md
      - Benchmarking: entrega-1/benchmarking.md
      - Histórias de Usuário (Backlog): entrega-1/historias-usuario.md
      - Protótipos (v0, v1 e v2): entrega-1/prototipos.md