site_name: Documentation Membership Area

theme:
  name: material

nav:
  - Início: index.md
  - Planejamento:
      - Home: planejamento/home.md
      - PM Canvas: planejamento/pm-canvas.md
      - Benchmarking: planejamento/benchmarking.md
      - Histórias de Usuário (Backlog): planejamento/historias-usuario.md
      - Protótipos (v0, v1 e v2): planejamento/prototipos.md